const fs = require('fs');
const path = require('path');

const doctorsFile = 'src/data/doctors.ts';
const indexFile = 'src/data/doctors/index.ts';
const doctorsDir = 'src/data/doctors';

const content = fs.readFileSync(doctorsFile, 'utf8');

// Find all positions of '{ id: "' (start of each doctor)
const doctorStartRegex = /\{\s*id:\s*"([^"]+)"/g;
let match;
const starts = [];
while ((match = doctorStartRegex.exec(content)) !== null) {
  starts.push({ id: match[1], index: match.index });
}

if (starts.length === 0) {
  console.error('No doctor objects found.');
  process.exit(1);
}

console.log(`Found ${starts.length} doctors.`);

const doctorIds = [];
for (let i = 0; i < starts.length; i++) {
  const { id, index } = starts[i];
  // Find the full object using brace matching
  let braceCount = 0;
  let inString = false;
  let stringChar = '';
  let lastChar = '';
  let end = index;
  for (let j = index; j < content.length; j++) {
    const char = content[j];
    if (!inString && (char === '"' || char === "'" || char === '`')) {
      inString = true;
      stringChar = char;
    } else if (inString && char === stringChar && lastChar !== '\\') {
      inString = false;
    } else if (!inString) {
      if (char === '{') braceCount++;
      if (char === '}') braceCount--;
      if (braceCount === 0) {
        end = j + 1;
        break;
      }
    }
    lastChar = char;
  }
  const objectStr = content.slice(index, end);
  const fileName = path.join(doctorsDir, `${id}.ts`);
  const exportContent = `export const ${id} = ${objectStr};\n`;
  fs.writeFileSync(fileName, exportContent);
  doctorIds.push(id);
  console.log(`Created ${fileName}`);
}

// Generate index.ts
const indexContent = `// Auto-generated by extract-doctors.cjs\n${doctorIds.map(id => `import { ${id} } from './${id}';`).join('\n')}\n\nexport const doctors = [\n${doctorIds.map(id => `  ${id},`).join('\n')}\n];\n\nexport {\n${doctorIds.map(id => `  ${id},`).join('\n')}\n};\n`;
fs.writeFileSync(indexFile, indexContent);
console.log(`\nUpdated ${indexFile}`);
console.log('Extraction complete!'); 