// Auto-generated by extract-doctors.cjs
import { abdykhadirov } from './abdykhadirov';
import { zhiengazina } from './zhiengazina';
import { nurgalieva } from './nurgalieva';
import { nugmetollanova } from './nugmetollanova';
import { toygulova } from './toygulova';
import { akhmetova } from './akhmetova';
import { erbolatova } from './erbolatova';
import { kairatbek } from './kairatbek';
import { adilbaev } from './adilbaev';
import { kozhakhmetova } from './kozhakhmetova';
import { aidarbekov } from './aidarbekov';
import { boltaev } from './boltaev';
import { tynyshtykova } from './tynyshtykova';
import { kokymbaeva } from './kokymbaeva';
import { fayzolda } from './fayzolda';
import { nartbaev } from './nartbaev';
import { utesheva } from './utesheva';
import { makenqyzy } from './makenqyzy';
import { asiya } from './asiya';
import { anes } from './anes';
import { kolkhozov } from './kolkhozov';
import { nigmetova } from './nigmetova';
import { burambaeva } from './burambaeva';
import { zhaparova } from './zhaparova';
import { askergazy } from './askergazy';
import { dosmuratov } from './dosmuratov';

export const doctors = [
  abdykhadirov,
  zhiengazina,
  nurgalieva,
  nugmetollanova,
  toygulova,
  akhmetova,
  erbolatova,
  kairatbek,
  adilbaev,
  kozhakhmetova,
  aidarbekov,
  boltaev,
  tynyshtykova,
  kokymbaeva,
  fayzolda,
  nartbaev,
  utesheva,
  makenqyzy,
  asiya,
  anes,
  kolkhozov,
  nigmetova,
  burambaeva,
  zhaparova,
  askergazy,
  dosmuratov,
];

export {
  abdykhadirov,
  zhiengazina,
  nurgalieva,
  nugmetollanova,
  toygulova,
  akhmetova,
  erbolatova,
  kairatbek,
  adilbaev,
  kozhakhmetova,
  aidarbekov,
  boltaev,
  tynyshtykova,
  kokymbaeva,
  fayzolda,
  nartbaev,
  utesheva,
  makenqyzy,
  asiya,
  anes,
  kolkhozov,
  nigmetova,
  burambaeva,
  zhaparova,
  askergazy,
  dosmuratov,
};
