// Auto-generated by extract-doctors.cjs
import { nurmatov } from './nurmatov';
import { tuyebayev } from './tuyebayev';
import { abdykhadirov } from './abdykhadirov';
import { zhiengazina } from './zhiengazina';
import { nurgalieva } from './nurgalieva';
import { nugmetollanova } from './nugmetollanova';
import { toygulova } from './toygulova';
import { akhmetova } from './akhmetova';
import { erbolatova } from './erbolatova';
import { kairatbek } from './kairatbek';
import { adilbaev } from './adilbaev';
import { kozhakhmetova } from './kozhakhmetova';
import { aidarbekov } from './aidarbekov';
import { boltaev } from './boltaev';
import { tynyshtykova } from './tynyshtykova';
import { kokymbaeva } from './kokymbaeva';
import { fayzolda } from './fayzolda';
import { volchkov } from './volchkov';
import { nartbaev } from './nartbaev';
import { utesheva } from './utesheva';
import { makenqyzy } from './makenqyzy';
import { khamitov } from './khamitov';
import { asiya } from './asiya';
import { anes } from './anes';
import { kolkhozov } from './kolkhozov';

export const doctors = [
  nurmatov,
  tuyebayev,
  abdykhadirov,
  zhiengazina,
  nurgalieva,
  nugmetollanova,
  toygulova,
  akhmetova,
  erbolatova,
  kairatbek,
  adilbaev,
  kozhakhmetova,
  aidarbekov,
  boltaev,
  tynyshtykova,
  kokymbaeva,
  fayzolda,
  volchkov,
  nartbaev,
  utesheva,
  makenqyzy,
  khamitov,
  asiya,
  anes,
  kolkhozov,
];

export {
  nurmatov,
  tuyebayev,
  abdykhadirov,
  zhiengazina,
  nurgalieva,
  nugmetollanova,
  toygulova,
  akhmetova,
  erbolatova,
  kairatbek,
  adilbaev,
  kozhakhmetova,
  aidarbekov,
  boltaev,
  tynyshtykova,
  kokymbaeva,
  fayzolda,
  volchkov,
  nartbaev,
  utesheva,
  makenqyzy,
  khamitov,
  asiya,
  anes,
  kolkhozov,
};
